export const ADD_NUMBER_REQUEST = 'ADD_NUMBER_REQUEST';
export const ADD_NUMBER_SUCCESS = 'ADD_NUMBER_SUCCESS';
export const ADD_NUMBER_FAILURE = 'ADD_NUMBER_FAILURE';

export const SUBTRACT_NUMBER_REQUEST = 'SUBTRACT_NUMBER_REQUEST';
export const SUBTRACT_NUMBER_SUCCESS = 'SUBTRACT_NUMBER_SUCCESS';
export const SUBTRACT_NUMBER_FAILURE = 'SUBTRACT_NUMBER_FAILURE';